"""ObsidianParser — Obsidian vault parser for the nimbus:: namespace.

Wraps vault_loader + the deterministic extraction logic from ast_extractor into
the v5.0 parser pipeline. Produces a ParseResult that can be written via any
StorageBackend.

Parse output:
  Nodes   — one TreeNode per VaultDocument (kind="note"|"knowledge") plus
             synthetic tag and category nodes (kind="tag"|"category"), all
             children of a virtual vault-root node.
  Edges   — lateral EXTRACTED edges: wikilinks, tagged_as, categorized_as,
             and explicit frontmatter relations (depends_on, supersedes, …).
             Structural contains edges are auto-generated by ParseResult.from_tree().

source must be the vault root directory.
"""

from __future__ import annotations

import hashlib
from pathlib import Path

from prism_rag.ingest.ast_extractor import (
    _RELATION_TYPES,
    _build_doc_index,
    _extract_inline_tags,
    _extract_wikilinks,
    _token_count,
)
from prism_rag.ingest.base_parser import Parser
from prism_rag.ingest.base_tree import ParseTree, TreeNode
from prism_rag.ingest.parse_result import EdgeRecord, ParseResult
from prism_rag.ingest.vault_loader import VaultDocument, load_vault


def _tag_node_id(tag: str) -> str:
    return f"tag:{tag}"


def _category_node_id(category: str) -> str:
    return f"category:{category}"


class ObsidianParser(Parser):
    """Parser for Obsidian vaults (nimbus:: namespace).

    Call parse(vault_root) to get a ParseResult for the entire vault.
    """

    @property
    def namespace(self) -> str:
        return "nimbus"

    def parse(self, source: Path) -> ParseResult:
        docs, _live_sha_set = load_vault(source)
        return self._build_result(docs, source)

    # ── Internal build ────────────────────────────────────────────────

    def _build_result(self, docs: list[VaultDocument], vault_root: Path) -> ParseResult:
        doc_index = _build_doc_index(docs)

        # Vault root node — content_hash is a stable fingerprint of all file hashes.
        vault_hash = hashlib.sha1(
            "".join(sorted(d.content_hash for d in docs)).encode()
        ).hexdigest()
        root = TreeNode(
            id=f"nimbus:vault:{vault_root.name}",
            kind="note",
            label=vault_root.name,
            content="",
            namespace="nimbus",
            source_file=str(vault_root),
            content_hash=vault_hash,
        )

        all_tags: set[str] = set()
        all_categories: set[str] = set()

        for doc in docs:
            kind = "knowledge" if doc.frontmatter.get("knowledge_id") else "note"
            meta: dict = {
                "frontmatter": doc.frontmatter,
                "tags": doc.frontmatter_tags,
            }
            if kind == "knowledge":
                meta["know_id"] = str(doc.frontmatter["knowledge_id"])

            root.add_child(TreeNode(
                id=doc.id,
                kind=kind,
                label=doc.label,
                content=doc.content,
                namespace="nimbus",
                source_file=str(doc.relative_path),
                content_hash=doc.content_hash,
                tokens=_token_count(doc.content),
                metadata=meta,
            ))

            all_tags.update(set(doc.frontmatter_tags) | _extract_inline_tags(doc.content))
            if doc.category:
                all_categories.add(doc.category)

        # Synthetic tag and category nodes — children of vault root so
        # ParseResult.from_tree() generates their contains edges automatically.
        for tag in sorted(all_tags):
            root.add_child(TreeNode(
                id=_tag_node_id(tag),
                kind="tag",
                label=f"#{tag}",
                content="",
                namespace="nimbus",
                source_file=str(vault_root),
            ))
        for cat in sorted(all_categories):
            root.add_child(TreeNode(
                id=_category_node_id(cat),
                kind="category",
                label=cat,
                content="",
                namespace="nimbus",
                source_file=str(vault_root),
            ))

        tree = ParseTree(root=root, namespace="nimbus", source_file=str(vault_root))
        extra_edges = self._build_lateral_edges(docs, doc_index)
        return ParseResult.from_tree(tree, parser_id="ObsidianParser", extra_edges=extra_edges)

    def _build_lateral_edges(
        self,
        docs: list[VaultDocument],
        doc_index: dict[str, str],
    ) -> list[EdgeRecord]:
        edges: list[EdgeRecord] = []

        for doc in docs:
            # Wikilinks
            for target, relation in _extract_wikilinks(doc.content):
                resolved = doc_index.get(target.lower())
                if resolved is None or resolved == doc.id:
                    continue
                edges.append(EdgeRecord(
                    source_id=doc.id,
                    target_id=resolved,
                    kind=relation,
                    confidence_tier="EXTRACTED",
                    confidence=1.0,
                    weight=1.0,
                    evidence=["wikilink"],
                ))

            # Tags (frontmatter + inline)
            doc_tags = set(doc.frontmatter_tags) | _extract_inline_tags(doc.content)
            for tag in doc_tags:
                edges.append(EdgeRecord(
                    source_id=doc.id,
                    target_id=_tag_node_id(tag),
                    kind="tagged_as",
                    confidence_tier="EXTRACTED",
                    confidence=1.0,
                    weight=1.0,
                    evidence=["tag"],
                ))

            # Category
            if doc.category:
                edges.append(EdgeRecord(
                    source_id=doc.id,
                    target_id=_category_node_id(doc.category),
                    kind="categorized_as",
                    confidence_tier="EXTRACTED",
                    confidence=1.0,
                    weight=1.0,
                    evidence=["frontmatter.category"],
                ))

            # Explicit typed relations from frontmatter.relations
            relations = doc.frontmatter.get("relations")
            if not isinstance(relations, dict):
                continue
            for rel_type in _RELATION_TYPES:
                targets = relations.get(rel_type)
                if not targets:
                    continue
                if isinstance(targets, str):
                    targets = [targets]
                elif not isinstance(targets, list):
                    continue
                for t in targets:
                    t_str = str(t).strip()
                    if not t_str:
                        continue
                    resolved_t = doc_index.get(t_str.lower())
                    if resolved_t is None or resolved_t == doc.id:
                        continue
                    edges.append(EdgeRecord(
                        source_id=doc.id,
                        target_id=resolved_t,
                        kind=rel_type,
                        confidence_tier="EXTRACTED",
                        confidence=1.0,
                        weight=1.0,
                        evidence=["frontmatter.relations"],
                    ))

        return edges
